apiVersion: v1
kind: Service
metadata:
  name: postgresql-external
  namespace: apacheanswerns##
  labels:
    version: 1.0.0
spec:
  selector:
   app: postgres
  ports:
    - protocol: TCP    
      port: 5432
      targetPort: 5432
  type: LoadBalancer      