apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres  
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: db0
            - name: POSTGRES_USER
              value: kyma
            - name: POSTGRES_PASSWORD
              value: kyma
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "postgres"
              subPath: postgres 
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: kyma-pgdata   

